version: '2.4'
services:
    qdrant:
      image: qdrant/qdrant
      restart: always
      ports:
        - 6333:6333
        - 6334:6334
      volumes:
        - ./qdrant:/qdrant/storage
      container_name: qdrant_pokemon